# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f48d8b75863fedd8eb1752399d20d83b2a25c5cace6c92674503db99095645e672944ca0b12a7d013c431a89d31e42f8ec7bd25c58dab6881e93bcac2ca10b9

test:
  secret_key_base: 0afb5441c2fa6f342d95f70be139cf489a960b3b4e5ad3e769fcefbc8ff10e807baf19122f56c0b407dae04968c68481ea9c933c9201d848385b4a40a64d0e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
